# Homepage scroll film: the client's intro video -> WebP frame sequences the page draws on a canvas.
# A frame sequence scrubs smoothly on every device (a scrubbed <video> freezes on iPhones and needs a special
# encode everywhere else). Run from the project root: python _research/hero/frames.py
#
# Source: the TensorPix upscale of the client's clip, 1920x1080 at 60 fps (same timing as the 720p original).
# Timing measured from the pixels (see progress.md): warp 0-2.7 s, slow-down to 4.9 s, beam ignites 4.9-5.6 s
# at x 50% / y 69%, floor line 5.6-6.8 s, chevrons 6.8-7.7 s, then almost no change until 10 s.
#
# Adaptive sampling: walk the 60 fps source and keep a frame whenever the picture has changed by THRESHOLD
# (mean absolute RGB difference, accumulated) since the last kept one, or MAXGAP source frames have passed.
# So the fast warp keeps nearly every frame, the calm second half a few per second, and consecutive kept frames
# always look alike: the page can crossfade neighbours while moving and rest on a real frame without ghosting.
# Writes the frames to site/static/img/home/seq/{d,m}/NNN.webp and the kept source-frame numbers to
# site/data/film.mjs (site.js maps film time onto them).
import subprocess, os, glob
import numpy as np
import imageio_ffmpeg
from PIL import Image

SRC = "_research/hero/intro-video.mp4"
OUT = "site/static/img/home/seq"
DATA = "site/data/film.mjs"
FF = imageio_ffmpeg.get_ffmpeg_exe()
W, H, FPS = 1920, 1080, 60
END, CALM = 480, 294          # 8.0 s: last sampled frame before the true last one; 4.9 s: the calm half starts
#       change threshold, max gap before / after CALM, crop box (None = full frame), quality before / after CALM
SETS = {"d": (10, (4, 6), None, 54, 64),
        "m": (13, (5, 7), (540, 0, 1380, 1080), 52, 60)}   # phone: centre 840x1080, covers portrait up to 0.78


def frames(w, h):
    """Stream the source as RGB frames, one at a time (the full-res clip is 3.7 GB decoded)."""
    p = subprocess.Popen([FF, "-hide_banner", "-loglevel", "error", "-i", SRC, "-an", "-vf", f"scale={w}:{h}",
                          "-f", "rawvideo", "-pix_fmt", "rgb24", "-"], stdout=subprocess.PIPE)
    while (buf := p.stdout.read(w * h * 3)) and len(buf) == w * h * 3:
        yield np.frombuffer(buf, np.uint8).reshape(h, w, 3)
    p.wait()


def pick(diff, threshold, maxgap):
    keep, acc = [0], 0.0
    for i in range(1, END + 1):
        acc += diff[i - 1]
        if acc >= threshold or i - keep[-1] >= maxgap[i >= CALM]:
            keep.append(i)
            acc = 0.0
    if keep[-1] != END:
        keep.append(END)
    return keep + [len(diff)]  # + the true last frame


small = np.stack([f.astype(np.float32) for f in frames(480, 270)])
keep = {}
for d, (threshold, maxgap, crop, *_q) in SETS.items():
    s = small if crop is None else small[:, :, crop[0] // 4:crop[2] // 4]
    keep[d] = pick(np.abs(s[1:] - s[:-1]).mean(axis=(1, 2, 3)), threshold, maxgap)

for d in SETS:
    os.makedirs(f"{OUT}/{d}", exist_ok=True)
    for f in glob.glob(f"{OUT}/{d}/*.webp"):
        os.remove(f)
index = {d: {n: i for i, n in enumerate(keep[d])} for d in SETS}
for n, frame in enumerate(frames(W, H)):
    for d, (_t, _g, crop, q_move, q_calm) in SETS.items():
        if n in index[d]:
            im = Image.fromarray(frame)
            if crop:
                im = im.crop(crop)
            im.save(f"{OUT}/{d}/{index[d][n]:03d}.webp", "WEBP", quality=q_move if n < CALM else q_calm, method=6)

with open(DATA, "w", encoding="utf-8", newline="\n") as f:
    f.write("// Generated by _research/hero/frames.py: the 60 fps source frames each homepage film frame was taken from.\n")
    f.write(f"export const FILM = {{ fps: {FPS}, " + ", ".join(f"{d}: [{','.join(map(str, keep[d]))}]" for d in SETS) + " };\n")
for d in SETS:
    files = glob.glob(f"{OUT}/{d}/*.webp")
    print(f"{d}: {len(files)} frames, {sum(map(os.path.getsize, files)) / 1e6:.2f} MB")
