# Bangladesh divisions -> SVG path data for the dealer map (site/data/bd-map.mjs).
# Source: geoBoundaries gbOpen BGD ADM1 (simplified), CC0. Run from the project root: python _research/geo/bd_map.py
import json, math
SRC = "_research/geo/bgd-adm1.geojson"
OUT = "site/data/bd-map.mjs"
NAMES = {"Chittagong": "Chattogram", "Barisal": "Barishal", "Rajshani": "Rajshahi"}
K, LAT0 = 100, 23.7                       # 100 map units per degree of latitude
COS = math.cos(math.radians(LAT0))        # equirectangular, true scale at Bangladesh's middle latitude

g = json.load(open(SRC, encoding="utf8"))
rings = lambda geom: geom["coordinates"] if geom["type"] == "MultiPolygon" else [geom["coordinates"]]
allpts = [pt for f in g["features"] for poly in rings(f["geometry"]) for ring in poly for pt in ring]
LON_MIN, LAT_MAX = min(p[0] for p in allpts), max(p[1] for p in allpts)
PAD = 6
proj = lambda lon, lat: ((lon - LON_MIN) * COS * K + PAD, (LAT_MAX - lat) * K + PAD)
W = round(max(proj(p[0], p[1])[0] for p in allpts) + PAD)
H = round(max(proj(p[0], p[1])[1] for p in allpts) + PAD)

def area_centroid(ring):
    a = cx = cy = 0
    for (x1, y1), (x2, y2) in zip(ring, ring[1:] + ring[:1]):
        c = x1 * y2 - x2 * y1; a += c; cx += (x1 + x2) * c; cy += (y1 + y2) * c
    a /= 2
    return abs(a), (cx / (6 * a), cy / (6 * a)) if a else ring[0]

out = []
for f in g["features"]:
    name = NAMES.get(f["properties"]["shapeName"], f["properties"]["shapeName"])
    d, best = [], (0, (0, 0))
    for poly in rings(f["geometry"]):
        outer = [proj(*p) for p in poly[0]]
        a, c = area_centroid(outer)
        if a < 4: continue                 # drop specks smaller than ~4 square map units (tiny chars)
        if a > best[0]: best = (a, c)
        for ring in poly:
            pts = [proj(*p) for p in ring]
            d.append("M" + "L".join(f"{x:.1f} {y:.1f}" for x, y in pts) + "Z")
    out.append({"name": name, "d": "".join(d), "cx": round(best[1][0], 1), "cy": round(best[1][1], 1)})

out.sort(key=lambda o: o["name"])
js = f"""// Generated by _research/geo/bd_map.py from geoBoundaries BGD ADM1 (CC0). Do not edit by hand.
// Equirectangular projection, {K} units per degree, scaled by cos({LAT0}°) east-west.
export const MAP = {{ w: {W}, h: {H} }};
export const project = (lat, lng) => [+((lng - {LON_MIN}) * {COS:.6f} * {K} + {PAD}).toFixed(1), +(({LAT_MAX} - lat) * {K} + {PAD}).toFixed(1)];
export const DIVISION_SHAPES = {json.dumps(out, separators=(",", ":"))};
"""
open(OUT, "w", encoding="utf8").write(js)
print(W, H, len(js) // 1024, "KB", [(o["name"], o["cx"], o["cy"]) for o in out])
